// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureTaskHub.Infrastructure.Data;

#nullable disable

namespace SecureTaskHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130030108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "07e5fcac-8993-438e-873f-8acfbce532dd",
                            ConcurrencyStamp = "2f4e9d57-8d6b-5c4f-0e3g-7b9d5c8f6e4b",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "20fd6e8a-2b25-4efa-a109-a67f339d5402",
                            ConcurrencyStamp = "1e3f8d46-7c5a-4b3e-9d2f-6a8c4b7e5d3a",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d633d3fa-5890-413d-a0b7-242601a49a75",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47287b02-ff20-4dc8-bf50-69da9d1a656a",
                            Email = "admin@demo.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DEMO.LOCAL",
                            NormalizedUserName = "ADMIN@DEMO.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ3h9d5WYzthMCKEbVqfZYGmEP4rdZdKcLhKYo3EqXz+uGqC8X1Pq5SiJ4KdVkzSLQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "38775744-6fe3-4f87-b8c8-ea3fcd7eb089",
                            TwoFactorEnabled = false,
                            UserName = "admin@demo.local"
                        },
                        new
                        {
                            Id = "495d56e4-43b1-4e54-9cef-10e917d28f63",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "054ec42a-c1df-4b3f-ad55-f300ec6a853a",
                            Email = "alice@demo.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE@DEMO.LOCAL",
                            NormalizedUserName = "ALICE@DEMO.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEGxF7p4M3NqK8yWjLZv5rQwXzB9cT2sH6vN1kP8oY4eD3mR7aJ9iU5tL2fO6wE1xKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a00fd73-7f7a-4719-9fd9-0e0d6a148efd",
                            TwoFactorEnabled = false,
                            UserName = "alice@demo.local"
                        },
                        new
                        {
                            Id = "21809ee3-a838-42e1-99b5-ad07b8deb31b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83ef9ad3-c995-479a-ac87-f41ef09796b6",
                            Email = "bob@demo.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB@DEMO.LOCAL",
                            NormalizedUserName = "BOB@DEMO.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEDn8K5r2TvH6pM9wJ3sX1cY7oB4eP8qL2fN6kR9iZ3tA5mG1uV7hO4jE6wD8cS2nLx==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4318e961-2a50-43fd-8f29-298a814a90fc",
                            TwoFactorEnabled = false,
                            UserName = "bob@demo.local"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d633d3fa-5890-413d-a0b7-242601a49a75",
                            RoleId = "07e5fcac-8993-438e-873f-8acfbce532dd"
                        },
                        new
                        {
                            UserId = "495d56e4-43b1-4e54-9cef-10e917d28f63",
                            RoleId = "20fd6e8a-2b25-4efa-a109-a67f339d5402"
                        },
                        new
                        {
                            UserId = "21809ee3-a838-42e1-99b5-ad07b8deb31b",
                            RoleId = "20fd6e8a-2b25-4efa-a109-a67f339d5402"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SecureTaskHub.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete quarterly security audit review",
                            OwnerUserId = "d633d3fa-5890-413d-a0b7-242601a49a75",
                            Status = "InProgress",
                            Title = "Review system security audit"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add new reporting features to admin dashboard",
                            OwnerUserId = "d633d3fa-5890-413d-a0b7-242601a49a75",
                            Status = "New",
                            Title = "Update admin dashboard"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Write and submit Q1 project proposal",
                            OwnerUserId = "495d56e4-43b1-4e54-9cef-10e917d28f63",
                            Status = "InProgress",
                            Title = "Complete project proposal"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Review pull requests from team members",
                            OwnerUserId = "495d56e4-43b1-4e54-9cef-10e917d28f63",
                            Status = "New",
                            Title = "Review code changes"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Organize monthly team sync",
                            OwnerUserId = "495d56e4-43b1-4e54-9cef-10e917d28f63",
                            Status = "Done",
                            Title = "Schedule team meeting"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Debug and fix authentication issue reported by users",
                            OwnerUserId = "21809ee3-a838-42e1-99b5-ad07b8deb31b",
                            Status = "InProgress",
                            Title = "Fix login bug"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Document new API endpoints for external developers",
                            OwnerUserId = "21809ee3-a838-42e1-99b5-ad07b8deb31b",
                            Status = "New",
                            Title = "Write API documentation"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update NuGet packages to latest stable versions",
                            OwnerUserId = "21809ee3-a838-42e1-99b5-ad07b8deb31b",
                            Status = "Done",
                            Title = "Update dependencies"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
